### ISSUE TITLE
Outputted fakes are not go-formatted

### ISSUE THREAD

**Issue by robdimsdale** [maxbrunsfeld/counterfeiter#11]
Can we run `go fmt` on the outputted files after creation?

**Comment by maxbrunsfeld** [comment]
Yeah, that's interesting. I thought that passing them through [`goimports`](https://github.com/bradfitz/goimports) would format them, but apparently not. I'd be open to running them through `go fmt`.

**Comment by glyn** [comment]
The Garden team ran into this too. Since we use multiple editors/IDEs, some of us have a git pre-commit hook which checks go files are formatted correctly. This complains about freshly generated counterfeiter files, which is a pain. (I've seend goimports format counterfeiter fakes when I didn't want it to, so please check your findings of goimports.)
