### ISSUE TITLE
Package names aren't being generated correctly

### ISSUE THREAD

**Issue by postables** [maxbrunsfeld/counterfeiter#122]
I'm working on generating mocks for the `BchrpcClient` interface specified [here](https://github.com/gcash/bchd/blob/master/bchrpc/pb/bchrpc.pb.go).

I'm using the following make target to handle mock generation:

```make
.PHONY: gen-mocks
gen-mocks:
	@echo "===================    regenerating     ==================="
	GO111MODULE=off go get -u github.com/maxbrunsfeld/counterfeiter
	counterfeiter -o ./mocks/bchrpc.mock.go \
		./bchrpc/pb BchrpcClient 
	@echo "===================          done           ==================="
```

Unfortunately, it doesn't appear counterfeiter is properly generating the package name and ends up generating this "bchd/bchrpc/pb"` when it should be `github.com/gcash/bchd/bchrpc/pb`

**Comment by joefitzgerald** [comment]
@postables Can you please provide more information about your environment?

1. It looks like you’re doing `GOPATH` based development and not using a go module?
1. What is your `GOPATH`?
1. What is the path to `bchrpc.pb.go` on your filesystem?
1. Are you using symlinks for any file or folder containing `bchrpc.pb.go` in order to place it in the `GOPATH`?

**Comment by joefitzgerald** [comment]
@postables I am going to close this issue, and will gladly re-open it if you can respond back with answers to my questions.
