### ISSUE TITLE
use import- instead of source-path

### ISSUE THREAD

**Issue by cryptix** [maxbrunsfeld/counterfeiter#16]
Hi,

I think using the import path would be handier than the filesystem path to locate the interface.

It can be looked up converted to a fs path fairly easy by using the [go/build](http://golang.org/pkg/go/build) package.

``` go
// findRelImport tries to find the import string in the $GOPATH
// and constructs a filepath relative to the current wroking directory
func findRelImport(imp string) string {
    p, err := build.Default.Import(imp, "", build.FindOnly)
    checkPanic(err)

    cwd, err := os.Getwd()
    checkPanic(err)

    p.Dir, err = filepath.Rel(cwd, p.Dir)
    checkPanic(err)

    return p.Dir
}
```

Having this made moving and renaming packages much more comfortable with other tools but I guess we should have both options for compatibility and flexibility.

I can whip up a preliminary PR if you agree.

**Comment by tjarratt** [comment]
For what it's worth, I often try to use the go import path, because other go tools have trained my brain to work that way.

It should be possible to support both by first looking for a valid filesystem path and falling back to the `GOPATH`, so there shouldn't be any backwards compatibility concerns.

**Comment by maxbrunsfeld** [comment]
Word. Hey @cryptix sorry I missed this issue from so long ago; I'm not coding go these days, so I haven't taken on anything substantial changes to counterfeiter.

@tjarratt Are you interested in adding the GOPATH thing? I'd definitely merge it.

**Comment by tjarratt** [comment]
@maxbrunsfeld I'm actually interested in adding a few small features to counterfeiter, including the proposed `GOPATH` change. We're finding counterfeiter to be incredibly valuable and I think it would benefit from having some additional polish to the experience of using it day to day.

Here's a (somewhat) short list of quality of life improvements I'd like to work on

* interactively prompt the user for an interface to fake if only one argument is given
* automatically fake the only interface in a file if it contains a single interface type
* warn users when fakes are generated that use unexpected types as arguments or return values
* allow first argument to be a directory, in addition to a file path
* allow first argument to be a path to a package on `GOPATH`

Oh, and I'm looking to add some integration tests as well.

Unsure what your thoughts are on any of those features, so this seems like a pretty reasonable way to bring this up.

**Comment by maxbrunsfeld** [comment]
:sparkles: Yeah, I'd be open to all of these.

I actually think for the `GOPATH` argument thing, we should probably just :fire: the ability to specify a file system path. It seems clearer to only have one way of doing things, and if people are finding the file-system path surprising, then I'd be in favor of just making it work like `go build` and other go CLI tools.

**Comment by cryptix** [comment]
:+1: on burning file system path. Even for the simple case of renaming a file or moving a type definition to another file, its much more usable to rely on the import path.

@tjarratt please make the interactive prompt just a new feature. Personally I rely on using it with `go generate`

**Comment by tjarratt** [comment]
@cryptix when you say "a new feature" do you mean a separate tool, or that you imagine a separate way of invoking it?

I'm mindful that existing users (especially those using `go generate`) abhor an interactive mode, because it has the possibility to break tools. 

Today, if you invoke counterfeiter with a single argument, it exits `1`, so it seems okay to me to make that interactive, and preserve the existing non-interactive behavior. It should also be possible to detect if the terminal is a TTY, and 

```shell
$ counterfeiter path/to/my/package.go

What file in `package.go` would you like to counterfeit?
1. Something
2. SomethingElse

> 2

Wrote `SomethingElse` to `fakes/something_else.go`

$
```

Thoughts? Concerns? I'm entirely open to doing this in a way that doesn't hurt existing users (even if that means making a separate tool).

**Comment by cryptix** [comment]
Hey @tjarratt,

> Today, if you invoke counterfeiter with a single argument, it exits 1, so it seems okay to me to make that interactive, and preserve the existing non-interactive behavior. It should also be possible to detect if the terminal is not a TTY, and fail gracefully.

Oh, Right! Invoking it that way is perfect then. No Concerns. :+1:

**Comment by joefitzgerald** [comment]
This is now the behavior of the package, because we're using `go/packages`, and it requires a package path, which can be either absolute or an import path.
