### ISSUE TITLE
Allow caller to set a custom output package for fakes

### ISSUE THREAD

**Issue by devoid** [maxbrunsfeld/counterfeiter#24]
The counterfeiter CLI allows you to specify `-o` and `--fake-name` flags. But it should also allow you to define the package name and path that is generated, for example:

```
$ counterfeiter github.com/my/package Something -p github.com/my/package/tests/fakes
Wrote `FakeSomething` to `github.com/my/package/tests/fakes/fake_something.go`
```

An additional complexity here is that I would like to be able to export the fakes to the same package as the interface definition. Reason: currently it is not possible to use counterfeiter-generated fakes in the package defining the interface (e.g. in unit tests) because this results in a cyclic dependency; allowing fakes to reside in the same package fixes this issue.

```
$ counterfeiter github.com/my/package Something -p github.com/my/package
Wrote `FakeSomething` to `github.com/my/package/fake_something.go`
```

**Comment by MrJoy** [comment]
+1 to this issue.  I'd love to be able to have `go generate` do all the work but right now I need a mish-mash of `go generate`, `mv`, `gofmt -r`, `sed`, and `goimports`.

**Comment by tjarratt** [comment]
@devoid @MrJoy isn't it only a cyclic dependency if you use your counterfeiter fakes in unit tests that aren't in the `mypackage_test` package?

`mypackage`
(has no imports)

`mypackage_test)
(import mypackage)
(import mypackagefakes)

`mypackagefakes`
(import mypackage)

I feel very strongly about *never* writing tests outside of the special `_test` package, but I can see why this would also be nice to have in general, especially if people are using `mv` and `sed` to get this stuff right.

I'd be happy to merge a PR for this behavior if anyone is interested. If you're not sure where to start, I'd also be happy to provide as much support and guidance as you like.

**Comment by MrJoy** [comment]
I honestly don't know what's going on here.  I'll see if there's sow thing
like that going on.  If there is such a situation, it's probably a
contortion to enable DI to facilitate the mocking of things in test.



-- 
Jon Frisby
Sent with Airmail

**Comment by MrJoy** [comment]
Hrm.  Yes, it looks like that may be what's going on here.  Our convention is to put the test code in the same package.  Oddly, while we use Counterfeiter heavily, we only seem to have a problem doing this with one particular fake.

**Comment by tjarratt** [comment]
Well I'm pretty pleased that you're using counterfeiter heavily. I certainly use it a lot, but one of the downsides of OSS is that you only hear from people when it stops working.

I think it would be nice to keep this issue open for a while to encourage discussion.

Personally, I am firmly opposed to this feature. Allow people to specify their own output package would encourage users to put the fakes in the same package, which is definitely an antipattern. (I personally believe the in convention over configuration for things like this, but can appreciate that others may disagree (and that I may be wrong).

**Comment by devoid** [comment]
@tjarratt I am not sure what you mean by the `_test` package? If you look at the Go std-library sources, e.g. [`container/ring`](https://golang.org/src/container/ring/) there is a ring_test.go file but the _package_ is still declared as `package ring`.

We too have been using Counterfeiter on several projects to great success; thank you, @maxbrunsfeld  and the other contributors for your work!

**Comment by tjarratt** [comment]
You can totally put your testfiles (e.g.: `ring_test.go`) in the package under test (e.g.: `package ring`). This allows you to reference unexported types in your package (which may be quite convenient if you're a library or framework author). This is absolutely a valid thing to do ... sometimes.

However, for the vast majority of applications and libraries, it's an awful code smell to put your tests directly in the package under test. Putting them in the `xyz_test` package is a much better practice because it forces you to use your exported types in the same way that a consumer of your package would, encouraging you to think holistically about the design of your system and how it feels to compose it together.

**Comment by devoid** [comment]
@tjarratt From a certain TDD point-of-view your approach may be more pure, but I think it may be a bit extreme to call it "awful code smell" to include tests in the same package as the implementation. This is what the Go stdlib does and how they document using the testing facilities. 

In any case I doubt that this will be fixed. I looked into doing it myself a few months ago but the code-generation process used here is complex, at least to me.

**Comment by tjarratt** [comment]
@devoid I agree. I don't always like to use such language, it always makes me feel awful, because I'm afraid of alienating others.

I think I felt so strongly at the time because I had just finished a project with someone that fiercely defended the practice of putting tests in the same package, purely for convenience, because they couldn't be bothered to think about whether or not to export their types. Putting in your tests in the same package sometimes, when you have very implementation details you want to test is reasonable, although I imagine it would be much more rare than putting tests in the `xyz_test` package.

With respect making counterfeiter easier to change and contribute to... do you think it would be easier to contribute if counterfeiter did not use the `go/ast` package, but instead used something like mustache templates to achieve the same effect?
