### ISSUE TITLE
Proposal: Fakes should be generated into a "___fakes" package

### ISSUE THREAD

**Issue by tjarratt** [maxbrunsfeld/counterfeiter#28]
I've been using counterfeiter a lot lately. One thing I notice is that once I generate fakes for two or more packages I'm likely to want to use fakes from multiple packages in a single test. This often means I have to alias my imports...

```go
import (
  "net/http"
  "os"

  dbFakes   "github.com/tjarratt/foo/database/fakes"
  httpFakes "github.com/tjarratt/foo/http/fakes"
)
```

This kind of sucks because existing tooling doesn't have a great answer to aliased packages (I'm looking at you, vim, emacs, Intelli-J and Sublime), and you constantly have to remember if you can use the `fakes` package name as is, or if you need to alias it.

What if (hear me out here), we followed the standard library model, and put our fakes into a "__fakes" package? For example, "net/http" has a "net/http/httptest" package that exposes some convenient test helpers. I believe that pivotal-golang/lager does this as well. This pattern seems to be emergent, and convenient since the `_fakes` package name is much less likely to collide, but still captures the same spirit of the standard library.

For existing code using the `fakes` package, we could write a "go fix" script that automatically rewrites your code and puts the source files in the (new) correct package. That should be a relatively painless way of dealing with the breakage for current users. (Tip of the hat to @robdimsdale for suggesting this).

I would like to issue a PR to counterfeiter that changes `fakes` to `xyzfakes` where `xyz` is the name of the package being faked.

Thoughts? Concerns? This is a breaking change, so I wanted to put this out here and solicit feedback first.

**Comment by maxbrunsfeld** [comment]
I haven't used go in a while, but off the top of my head, this seems like a great improvement. Maybe `/cc` any teams at pivotal that you know of that use counterfeiter to get their input?

**Comment by robdimsdale** [comment]
@tjarratt I didn't realize I had suggested the `go fix` script, but if I helped in some manner I'm glad to hear that.

Personally I like this proposal - I think all the reasons @tjarratt highlighted make sense. I've felt some pain around importing fakes under aliases, and I think this proposal addresses that.

I am a little bit less concerned about breaking changes to binaries than I am to libraries, as updating the binary doesn't cause breaking changes until the next time they are invoked, but I appreciate calling out the breaking change in a proposal before the code is modified.

Looking to the implementation, it sounds like for package `foo` we would rename the `foo/fakes` directory to `foo/footest` and the corresponding package in the generate file from `package fakes` to `package footest`?

**Comment by tjarratt** [comment]
@robdimsdale, thank you for clarifying the proposal; that's exactly what I meant to convey.

Both the directory and package name should change to `foofakes` so it's consistent. While you *could* choose to name your package and directory differently, it's certainly a lot more convenient (and idiomatic, arguably) to keep them the same.

**Comment by julz** [comment]
fwiw we've found that the current behaviour drives us to define interfaces at the client side where possible (rather than the provider side), which I think tends to make code more flexible and a bit more idiomatic (define what you need as an interface; be explicit - i.e. use a struct etc - about what you provide), so I view the current behaviour as fine -- and it's fairly easy to override with the `-o` flag where you want different behaviour. 

Having said that changing it doesn't hurt our use case (it just isn't really needed by it) and helps the alternate use case so I don't feel super-strongly about this. It _does_ seem like a shame to change the default behaviour (and therefore any existing users next time they go generate) when simply adding a flag (`-t` or something) to do this would work fine, though..

**Comment by tedsuo** [comment]
I would prefer "foofakes" rather than "footest" because it contains no foo tests and I will be importing it into my foo tests, and I will be confused basically all the time. I don't think it's an accurate enough name to scale well, I wish we had named the "lagertest" package "ginkgolager" as that would have saved some confusion there too.

Also - just pointing out there's no need for a "go fix" as nothing will be broken after this change. The code doesn't care where it lives after it is generated, this just effects the default for where the code goes. We already manually do this name change using the `-o` option in our go:generate directives on diego. I'm sure a rewriter would be handy if you wanted to switch in bulk, just not necessary. Unless I'm missing something?

2 :+1: on changing the default though!

**Comment by tedsuo** [comment]
Ok I think I figured out your breaking change.  You'll be running default go:generate directives you've already made and they will start spitting fakes out in a new spot, correct?

**Comment by zachgersh** [comment]
I also am not for or against this change, decidedly neutral in fact. I do wonder if this could just be another configuration option that a user can default to if they feel so inclined?

Believe we've avoided having to alias fakes by just having one top-level fakes package that holds all of the fakes. Easier to navigate but less fine grained control as multiple packages now depend on a shared fake.

**Comment by tjarratt** [comment]
@zachgersh that's interesting. I've never thought of keeping all of my fakes in one top-level package. Part of me wonder if that's a brilliant idea, or an anti-pattern. Suppose I'll need to try it on my next project and find out!

I mostly want to improve the default behavior of counterfeiter so that end-users need to do fewer customizations like you described. So long as it Does The Right Thing™ by default and sets you up for success in writing tests, and plays nicely with other parts of the go ecosystem, I think it's working well. Always needing to alias packages, or specify that you want them in "this" fakes package, versus another feels like a case of the tool relying too much on configuration over convention.

I must say that I do appreciate your feedback though. Thank you for chiming in, even to say that you felt "decidedly neutral". It's important to hear all points of view.

**Comment by tjarratt** [comment]
@tedsuo correct, the default `go generate` directives will be different once someone installs the new version of counterfeiter. I think of that as the happy default path using counterfeiter.

I like your idea of using `foofakes`. It's similar in spirit to the stdlib, but also captures what it is (fakes for the `foo` package). Thanks for suggesting that!

**Comment by tjarratt** [comment]
Thanks for providing feedback @maxbrunsfeld @tedsuo, @xenophex, @zachgersh, @Amit-PivotalLabs, @julz, @robdimsdale. 

I really appreciate you all coming together, looking at this, and helping me improve counterfeiter.
