### ISSUE TITLE
Test script does not run generator or locator tests

### ISSUE THREAD

**Issue by tomwhoiscontrary** [maxbrunsfeld/counterfeiter#32]
The test script, as run by Travis, [runs the tests like this](https://github.com/maxbrunsfeld/counterfeiter/blob/master/scripts/test.sh#L25):

```
go test -race -v . ./arguments ./integration
```

This does not run the tests in the generator or locator packages. Should it?

**Comment by tjarratt** [comment]
Thanks for pointing this out, @tomwhoiscontrary. That was *totally* not the intention there. 

I really appreciate the second set of eyes here, thanks for helping make counterfeiter great again!

I've since changed the test script to just be `go test -race -v ./...` which should capture this package and all of the others. I also took the liberty of adding some "bootstrap" tests for ginkgo, which ensures these run correct with `go test`.
