### ISSUE TITLE
Race condition when changing stubs across goroutines

### ISSUE THREAD

**Issue by chendrix** [maxbrunsfeld/counterfeiter#44]
``` go
package race_test

import (
    "github.com/yourcode/yourcodefakes"
    . "github.com/onsi/ginkgo"
)

var _ = Describe("data race", func() {
    It("has a race condition", func() {
        myHandler := new(yourcodefakes.FakeHandler)

        go func() {
            for {
                myHandler.SomeMethod()
            }
        }()

        myHandler.SomeMethodStub = func() string {
            return "some string"
        }
    })
})
```

Is there a preferred way to change the stub without causing a race condition? We experimented with exposing the mutex for `SomeMethod` by manually modifying the generated counterfeiter fakes, and locking when reassigning `SomeMethodStub`, eg:

``` go
                myHandler.SomeMethodMutex.Lock()
        myHandler.SomeMethodStub = func() string {
            return "some string"
        }
                myHandler.SomeMethodMutex.Unlock()
```

This fixes the race condition but obviously this requires editing the fake (non-ideal).

If we hid the re-assignment of the stub into a method, we could Lock/Unlock it in that function instead.

``` go
// This file was generated by counterfeiter
package yourcodefakes

import (
    "sync"

    "yourcode"
)

type FakeHandler struct {
    someMethodStub        func() string
    someMethodMutex       sync.RWMutex
    someMethodArgsForCall []struct{}
    someMethodReturns     struct {
        result1 string
    }
    invocations      map[string][][]interface{}
    invocationsMutex sync.RWMutex
}

func (fake *FakeHandler) SomeMethod() string {
    fake.someMethodMutex.Lock()
    fake.someMethodArgsForCall = append(fake.someMethodArgsForCall, struct{}{})
    fake.recordInvocation("SomeMethod", []interface{}{})
    fake.someMethodMutex.Unlock()
    if fake.someMethodStub != nil {
        return fake.someMethodStub()
    } else {
        return fake.someMethodReturns.result1
    }
}

func (fake *FakeHandler) SomeMethodCalls(stub func() string) {
      fake.someMethodMutex.Lock()
      defer fake.someMethodMutex.Unlock()

      fake.someMethodStub = stub
}

...

```

**Comment by tjarratt** [comment]
Wow. Never thought of this use case. 

I suppose in an ideal world this wouldn't ever come up, but if you ONLY need to change the return value you could use the MyMethodReturns method. If that doesn't already have a mutex it would be pretty straightforward to add it. 

Lacking that, maybe the go routine could be fired from a JustBeforeEach function? That way you wouldn't have a race condition at all. 

Sent From A Very Small Keyboard

**Comment by chendrix** [comment]
In our condition, the "go routine" is actually an RPC server spun up in a new goroutine, which fires the offending code when an RPC client makes a call for that function.

**Comment by maxbrunsfeld** [comment]
I sometimes found it convenient to assign the stubs on construction, via a struct literal. It also seems uncommon that you'd need to switch to a stub to point to a different function mid-test. That's why I made those fields public initially. I'm open to the possibility that encapsulating them is more useful. Curious about other people's opinions on this.

**Comment by maxbrunsfeld** [comment]
Also, I think your suggested API makes total sense, @chendrix 👍.

**Comment by chendrix** [comment]
So we were able to "fix" the race condition by fiddling with `BeforeEach`/`JustBeforeEach` to make sure we're not technically changing the stub *after* we've already started the RPC server in that other goroutine, which was the suggestion that @tjarratt had.

I still think there's some potential value in encapsulating the setter, to provide consistent access safely behind the mutex.

**Comment by maxbrunsfeld** [comment]
Ok, so it seems like in your case, a mutex it isn't really necessary. The change you proposed change is simple enough, though, so I wouldn't be opposed. If that method were added, I *kinda* think that the stub fields should be private, to avoid redundancy. But that would cause a breaking change in the interfaces of any fakes that were regenerated.

Since I'm not *using* counterfeiter anymore, what does everyone else think about breaking API changes in the generated fakes? Are people regenerating their fakes on a regular basis, like as part of their build? If so, would it be problematic to have to update tests to use the stub setters after bumping counterfeiter?

**Comment by tjarratt** [comment]
[I started versioning counterfeiter on gopkg.in](http://gopkg.in/maxbrunsfeld/counterfeiter.v1) a few iterations ago, although I have been TERRIBLE at 

* telling other people
* keeping the versions up to date

Most projects I've been on regenerate their fakes on each build, and just don't check them in (or they do both, if they want them to be checked in so they don't need to run `go generate`). In this case... this seems like a big enough change that it would be marked as v3, since so many tests would stop compiling.

**Comment by tjarratt** [comment]
Also, I'm glad you came over to comment on this issue @maxbrunsfeld. It's good to hear your voice again and see that you still care about counterfeiter. It's made a lot of us back at Labs very happy to have this tool.

**Comment by paulcwarren** [comment]
Actually I believe that we ran into this today but using the standard `SomeMethodReturns` rather than `SomeMethodStub` as in:-

```
package race_test

import (
    "github.com/yourcode/yourcodefakes"
    . "github.com/onsi/ginkgo"
)

var _ = Describe("data race", func() {
    It("has a race condition", func() {
        myHandler := new(yourcodefakes.FakeHandler)

        go func() {
            for {
                myHandler.SomeMethod()
            }
        }()

        myHandler.SomeMethodReturns("some string")
    })
})
```

The race condition is between the go routine calling `myHandler.SomeMethod()` and the line in `SomeMethodReturns` that sets the stub to nil.

Just for the record in our tests we are faking out services that return a changing status over time to, for example, indicate that the service is available and then unavailable and then available again, etc

**Comment by mcwumbly** [comment]
We just ran into this as well.

I went ahead and edited the generated code for the time being:

https://github.com/cloudfoundry-incubator/cf-networking-release/commit/bccc1fe48754ad7311231a758a63e0e12cca6a8b

We'll likely discuss this further and see if there are other ideas on our team for a better way to handle this.

Curious whether anyone's opinions here have shifted or further solidified since this discussion was last active about a year ago.

**Comment by tjarratt** [comment]
@mcwumbly I'm really really torn on this issue. None of the options I've thought of really make me happy.

Option 1: every counterfeiter fake has to acquire a mutex before a `FooReturns("bar")` invocation.
Option 2: add some sort of `--stubs-use-mutexes` flag that users would need to remember to use.

I don't like Option 1 because not every test case needs that, and we're trading performance for correctness. I don't like Option 2 because I feel like it forces the cognitive load onto users of counterfeiter.

As I started to think about how I would test this, I started to think about how changing, say, the return value of a status (like @paulcwarren described) really felt like a write operation to a channel.

Now I'm reading through some generated code and wondering if it's possible to use channels internally to make this easier (and maybe sufficiently performant for unit tests).

I also discovered that we (I) merged in [a PR five months ago](https://github.com/maxbrunsfeld/counterfeiter/pull/62) to allow [setting specific return values by call order](https://github.com/maxbrunsfeld/counterfeiter/commit/0e5df94929e053c66342ad646cb594343c7c6eaa). I can imagine that might help in these situations, but upon reflection, I don't really like forcing users to have to reason about WHICH call in order returns which value - that really feels like a lot of cognitive load for me.

I think my personal solution (strong emphasis on personal, because I haven't validated that anyone else would use this) would be to build something like [Mockito's](http://www.baeldung.com/mockito-behavior) `when` method for Counterfeiter. There's already an open issue for this on [gcounterfeiter](http://github.com/tjarratt/gcounterfeiter), my matcher library for fakes, but I haven't found the time to invest in making this happen.

**Comment by mcwumbly** [comment]
Hey @tjarratt 👋 

> I also discovered that we (I) merged in a PR five months ago to allow setting specific return values by call order.

Yeah, I actually swapped out a custom stub for that feature in the same commit (see [this line](https://github.com/cloudfoundry-incubator/cf-networking-release/commit/bccc1fe48754ad7311231a758a63e0e12cca6a8b#diff-f9389b3ec5d5acce9d47eecc6d91e4f6R119)).  But I'm not sure that's sufficient for the other cases (it may be... definitely worth looking at).

> I think my personal solution (strong emphasis on personal, because I haven't validated that anyone else would use this) would be to build something like Mockito's when method for Counterfeiter. 

Having used mockito in the past, I'd be a fan of this.

> Option 2: add some sort of --stubs-use-mutexes flag that users would need to remember to use.
> I don't like Option 2 because I feel like it forces the cognitive load onto users of counterfeiter.

I don't think think this would be too much extra load.  For the few times this is needed, a google search that leads to that option would be fine with me...

> gcounterfeiter, my matcher library for fakes

Oooh, I like this too:

> `Expect(myFake).To(HaveReceived("Something").With("arg1", 0))`

**Comment by maxbrunsfeld** [comment]
@tjarratt Just to clarify, mutexes have are always been used by inside of generated accessor methods like `FooReturns()` and `FooCallCount()`. I believe the only question is about whether we should generate additional thread-safe accessor methods for setting stub functions.

I still like @chendrix's idea of introducing a `FooCalls` method for setting the stub function. The only downside of this, I think, would be that it would introduce some redundancy with the public `FooStub` field, so we'd probably want to make that field private, which would break backwards compatibility.

@tjarratt Now that you've introduced some kind of versioning, this might not be too big of a deal.

**Comment by joefitzgerald** [comment]
I'm inclined to add `Lock` / `Unlock` calls on the mutex per https://github.com/cloudfoundry/cf-networking-release/commit/bccc1fe48754ad7311231a758a63e0e12cca6a8b. Any objections to this?
