### ISSUE TITLE
Counterfeiter uses GOPATH as import path for embedded interfaces from packages in vendor

### ISSUE THREAD

**Issue by beatrichartz** [maxbrunsfeld/counterfeiter#50]
When embedding interfaces, counterfeiter resolves the package path to packages in the GOPATH for vendored libraries. The expected behaviour would be that it resolves these package paths to vendor first before looking in the GOPATH. This can lead to subtle issues like the wrong fake being generated for interfaces with embedded interfaces from vendored libraries because another version of the package happens to be installed in the GOPATH as well.

I've reproduced the issue here: [github.com/beatrichartz/counterfeiter-vendor-issue](https://github.com/beatrichartz/counterfeiter-vendor-issue)

**Comment by davidje13** [comment]
This issue can be worked around by adding multiple folders to the GOPATH, but since "/src" is appended to each folder, it is not a perfect solution for the standard vendor folder.

The best workaround I have found so far:

```
mkdir vendor_gopath
mv vendor vendor_gopath/src # Note: cannot symlink this, since the symlink will not be followed
# GOPATH must be absolute, and make vendor take priority by listing it first
GOPATH="$(pwd)/vendor_gopath/src:$GOPATH" go generate <...>
mv vendor_gopath/src vendor
rm -rf vendor_gopath
```

Pretty ugly; it makes a new folder structure which is compatible with the idea of a gopath and temporarily moves the vendor folders into it. Counterfeiter is then able to run correctly. Can be made a bit safer by using exit hooks in a script, etc. But still not great.

Looks like this could be fixed by changing locator/locator.go's goSourcePaths method to include any `vendor` folders which are in an ancestor folder of the file being operated on. Doesn't seem like a trivial change since nothing in that source currently knows the path of the file.

**Comment by tjarratt** [comment]
Didn't mean to close this so abruptly.

I just verified manually that the repo you lovingly created to demonstrate this problem works now; once `counterfeiter` is updated, you can `go generate` even without the `github.com/ory-am/fosite` package on your `GOPATH`, which is pretty neat.

All credit to @sykesm for contributing the fix, all I did was tap a button.

Can you verify this works for you @beatrichartz? I could close this now, but I generally don't like to close issues on behalf of a reporter; it feels rude to me because as an end user, you should have the ultimate say in whether or not software works for you.

**Comment by beatrichartz** [comment]
@tjarratt thanks and apologies for the late reply, did only just see this in notifications. The example works now, awesome.

@seadowg did you see this ^^ ?
