### ISSUE TITLE
Tests are not locally rerunnable

### ISSUE THREAD

**Issue by BooleanCat** [maxbrunsfeld/counterfeiter#59]
Running the test suit with ./scripts/test.sh works the first time but hangs on race condition the second time.

I was able to rerun the tests after running `git clean -fx`

**Comment by tjarratt** [comment]
Yep, I am definitely seeing this as well after I upgraded my workstation to golang 1.7

They pass without the race flag, which seems to imply that either 

* the implementation has changed to have race conditions
* the golang race detector changed and can now hang

It's probably a good idea to make sure we clean up our test fixtures after we use them, rather than forcing users to remember to `git clean-fx` after the fixtures are no longer being used. I've just pushed a commit for that, but haven't had time to dig into the race detection issue.

**Comment by tjarratt** [comment]
I managed to narrow this down today to JUST the tests in the counterfeiter package itself. One of the 19 tests in `counterfeiter_test.go`.

**Comment by tjarratt** [comment]
That was one hell of a race condition.

Thank you *so much* for filing this issue @BooleanCat. I really, really appreciate the help in keeping counterfeiter's tests green. Even if it's a simple act like filing an issue, it means a lot to me.
