### ISSUE TITLE
Remove "fix" directory

### ISSUE THREAD

**Issue by madamkiwi** [maxbrunsfeld/counterfeiter#60]
If publish new version or tag a new release, remove the fix directory so tab completion works better.

**Comment by tjarratt** [comment]
This is a great point, we probably haven't needed this in a while since anyone that had generated fakes from before that fix is likely to have already migrated their test doubles.

The exact issue that @madamkiwi and I were trying to capture here is that there are top level `fix` and `fixtures` directories, and the user experience as a dev in the top level directory of counterfeiter is pretty crummy.

**Comment by tjarratt** [comment]
Thank you @madamkiwi for writing this issue this while we were pairing on aliased imports back in January. Much appreciated!
