### ISSUE TITLE
When the default GOPATH is used, counterfeiter fails with Path '<path here>' is not on GOPATH

### ISSUE THREAD

**Issue by michellescripts** [maxbrunsfeld/counterfeiter#80]
Reproduction:

* `go get -u github.com/blevesearch/bleve/...`
* `//go:generate counterfeiter -o ./fake_bleve_index.go "github.com/blevesearch/bleve.Index"`
* Observe error
* `export GOPATH="$HOME/go"`
* Observe no error

**Comment by tjarratt** [comment]
Thanks for sharing your issue @michellescripts. Out of curiosity - what's your original `$GOPATH` value before you export that environment variable ?

My understanding (and admittedly, I haven't been writing professional Go for about two years...) is that [the best practice is to always set](https://github.com/golang/go/wiki/GOPATH) `$GOPATH` to the directory where your non-GOROOT code will live.

From my perspective, this is working as intended, although I can empathize and appreciate that this might not be the kindest way to message this failure to a user.

Can you maybe tell me a bit about what you think about you observe "Path <path here> is not on GOPATH" message ? Is there perhaps a more clear way of wording this ? How might you express this in words so that someone else might be enlightened ?

**Comment by michellescripts** [comment]
@tjarratt In `go 1.8`, a default `GOPATH` was added for scenarios when the `GOPATH` environment variable is unset: https://rakyll.org/default-gopath/

So when `GOPATH` is unset, we should assume `$HOME/go` on Unix, `%USERPROFILE%\go` on Windows.

**Comment by tjarratt** [comment]
Thanks @michellescripts - you'd helped educate me about some cool new stuff in golang that I haven't seen before. The last time I was really doing active go development was around go 1.6, so I must have missed this change.

I'll be tackling this very soon (it's next on my list of features to add to counterfeiter), but I don't have a ETA for when it will land, given that I have a few other high priority commitments in my office, and I just got back from vacation.

**Comment by tjarratt** [comment]
Okay, turns out this was actually quite easy, it was only a one line change. 😓 

If you're still interested in this, would you like to try updating counterfeiter and see if this works for your use case now, @michellescripts ? I believe this should work as you expected now. 

I'm super curious, since I've never had the opportunity to talk to other golang developers that are using this new feature (the default `GOPATH`).

**Comment by joefitzgerald** [comment]
This is fixed.
