### ISSUE TITLE
Added counterfeiter version to DO NOT EDIT lines

### ISSUE THREAD

**Issue by ryanrolds** [maxbrunsfeld/counterfeiter#99]
Adding version, like so (`// Code generated by counterfeiter v6.0.1. DO NOT EDIT.`), would be helpful when working cross-team/project and improve transparency/debugability.

Being able to `grep` the fakes and easily determine the version used will help teams manage their versions as well as debug issues with the fakes generated by counterfeiter.

It is sometimes desirable to not regenerate all fakes with a different version, creating a multi-thousand line PR. Knowing the version of counterfeiter used to generate the existing fakes would allow developers to match version, creating a smaller set of changes in the PR.

**Comment by joefitzgerald** [comment]
The issue with this is that all version updates for counterfeiter would trigger large change sets for no material difference. I understand the desire but I’m not sure this is the best solution. 

The good news is that with go modules you can express the counterfeiter version you are using in your go.mod so that you get reproducible and deterministic outcomes. This is my recommended solution to the issue, albeit one that may be more feasible in go 1.12.
